name: Deploy Nginx to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2.pem
          chmod 400 ~/.ssh/ec2.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Nginx on EC2
        run: ssh -i ~/.ssh/ec2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo yum update -y || sudo apt update -y
            sudo yum install nginx -y || sudo apt install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx
          EOF

      - name: Deploy custom webpage
        run: scp -i ~/.ssh/ec2.pem index.html \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/index.html

          ssh -i ~/.ssh/ec2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo mv /tmp/index.html /var/www/html/index.html
            sudo systemctl restart nginx
          EOF
